version: '3.7'

volumes:
  fs-db:
    external: true

services:
  
  backend:
    container_name: fs_backend
    image: fs_backend
    build:
      context: /backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      # Source code
      - "./backend/:/backend/"
    depends_on:
      - db


  redis:
    image: redis
    environment:
      - TZ=Europe/Moscow
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - backend

  celery_worker:
    container_name: celery_worker
    build: ./backend
    command: celery -A services worker -l DEBUG
    volumes:
      - "./backend/:/backend/"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - backend
      - redis

  flower:
    container_name: flower
    build: ./backend
    command: bash -c 'celery -A services flower --port=5555'
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
    - backend
    - redis
    - celery_worker